version: "3.9"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      # name cluster and node
      - "cluster.name=MainCluster"
      - "node.name=FirstNode"
    networks:
      - es-net
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.2.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  es_data:

networks:
  es-net:
    driver: bridge